"""make_discipline_type_nullable

Revision ID: 0bcd6f13061f
Revises: 2aa6c7c2ce66
Create Date: 2026-02-18 23:03:32.743072

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0bcd6f13061f"
down_revision: str | None = "2aa6c7c2ce66"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trainers", "discipline_type", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trainers", "discipline_type", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    # ### end Alembic commands ###
