"""add_exercise_sets

Revision ID: 2aa6c7c2ce66
Revises: 216545cbc03c
Create Date: 2026-02-06 15:05:10.302638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa6c7c2ce66'
down_revision: Union[str, None] = '216545cbc03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('session_group_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(session_id IS NOT NULL AND session_group_id IS NULL) OR (session_id IS NULL AND session_group_id IS NOT NULL)', name='check_set_session_xor_group'),
    sa.ForeignKeyConstraint(['session_group_id'], ['session_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('session_exercises', sa.Column('exercise_set_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session_exercises', 'exercise_sets', ['exercise_set_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_exercises', type_='foreignkey')
    op.drop_column('session_exercises', 'exercise_set_id')
    op.drop_table('exercise_sets')
    # ### end Alembic commands ###
