"""add_client_profile_payment_and_session_doc_fields

Revision ID: b5739d11cb56
Revises: 44650287117e
Create Date: 2026-02-04 11:39:05.011458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5739d11cb56'
down_revision: Union[str, None] = '44650287117e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('sessions_paid', sa.Integer(), nullable=False),
    sa.Column('amount_cop', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clients', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.add_column('clients', sa.Column('birth_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clients', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('height_cm', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('training_sessions', sa.Column('is_paid', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('training_sessions', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('training_sessions', sa.Column('session_doc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_sessions', 'session_doc')
    op.drop_column('training_sessions', 'paid_at')
    op.drop_column('training_sessions', 'is_paid')
    op.drop_column('clients', 'weight_kg')
    op.drop_column('clients', 'height_cm')
    op.drop_column('clients', 'gender')
    op.drop_column('clients', 'birth_date')
    op.drop_column('clients', 'photo_url')
    op.drop_table('payments')
    # ### end Alembic commands ###
