"""add logo_url to trainers

Revision ID: ce5efdf7acfa
Revises: 001
Create Date: 2026-02-03 00:59:23.294217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce5efdf7acfa'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('clients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_clients_phone'), table_name='clients')
    op.drop_index(op.f('idx_clients_trainer'), table_name='clients', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('locations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_locations_place_id'), table_name='locations', postgresql_where='(google_place_id IS NOT NULL)')
    op.drop_index(op.f('idx_locations_trainer'), table_name='locations')
    op.alter_column('trainer_apps', 'theme_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('trainer_apps', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trainer_apps', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_apps_trainer'), table_name='trainer_apps')
    op.add_column('trainers', sa.Column('logo_url', sa.String(length=255), nullable=True))
    op.alter_column('trainers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('trainers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trainers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_trainers_email'), table_name='trainers', postgresql_where='(email IS NOT NULL)')
    op.drop_index(op.f('idx_trainers_google_id'), table_name='trainers', postgresql_where='(google_id IS NOT NULL)')
    op.drop_index(op.f('idx_trainers_phone'), table_name='trainers')
    op.alter_column('training_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('training_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_sessions_client'), table_name='training_sessions')
    op.drop_index(op.f('idx_sessions_trainer_date'), table_name='training_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_sessions_trainer_date'), 'training_sessions', ['trainer_id', 'scheduled_at'], unique=False)
    op.create_index(op.f('idx_sessions_client'), 'training_sessions', ['client_id'], unique=False)
    op.alter_column('training_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('training_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_trainers_phone'), 'trainers', ['phone'], unique=False)
    op.create_index(op.f('idx_trainers_google_id'), 'trainers', ['google_id'], unique=False, postgresql_where='(google_id IS NOT NULL)')
    op.create_index(op.f('idx_trainers_email'), 'trainers', ['email'], unique=False, postgresql_where='(email IS NOT NULL)')
    op.alter_column('trainers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trainers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trainers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('trainers', 'logo_url')
    op.create_index(op.f('idx_apps_trainer'), 'trainer_apps', ['trainer_id'], unique=False)
    op.alter_column('trainer_apps', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trainer_apps', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trainer_apps', 'theme_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_index(op.f('idx_locations_trainer'), 'locations', ['trainer_id'], unique=False)
    op.create_index(op.f('idx_locations_place_id'), 'locations', ['google_place_id'], unique=False, postgresql_where='(google_place_id IS NOT NULL)')
    op.alter_column('locations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_clients_trainer'), 'clients', ['trainer_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_clients_phone'), 'clients', ['trainer_id', 'phone'], unique=False)
    op.alter_column('clients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
