"""add discipline_type to trainer

Revision ID: dffbdc1e749f
Revises: f949ccc003b0
Create Date: 2026-02-05 18:12:19.993734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dffbdc1e749f'
down_revision: Union[str, None] = 'f949ccc003b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('trainers', sa.Column('discipline_type', sa.String(length=50), nullable=True))
    
    # Set default value for existing trainers (use 'bmx' as default)
    op.execute("UPDATE trainers SET discipline_type = 'bmx' WHERE discipline_type IS NULL")
    
    # Make column non-nullable
    op.alter_column('trainers', 'discipline_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainers', 'discipline_type')
    # ### end Alembic commands ###
