"""Add Google Auth fields to Trainer

Revision ID: e7bfc4ca7318
Revises: ce5efdf7acfa
Create Date: 2026-02-03 23:52:31.671866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7bfc4ca7318'
down_revision: Union[str, None] = 'ce5efdf7acfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainers', sa.Column('google_refresh_token', sa.String(), nullable=True))
    op.add_column('trainers', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('trainers', sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainers', 'token_expiry')
    op.drop_column('trainers', 'google_access_token')
    op.drop_column('trainers', 'google_refresh_token')
    # ### end Alembic commands ###
